### ISSUE TITLE
npm install failed on osx 10.11

### ISSUE THREAD

**Issue by yinrong** [pkrumins/node-des#4]
```
$ npm i des

> des@3.1.0 install /Users/yinrong/test/node_modules/des
> node-gyp rebuild

fg
  CXX(target) Release/obj.target/des/src/des-module.o
../src/des-module.cpp:13:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/yinrong/.node-gyp/5.0.0/include/node/v8.h:889:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/des-module.cpp:14:37: error: no member named 'New' in 'v8::String'
    return Exception::Error(String::New(msg));
                            ~~~~~~~~^
../src/des-module.cpp:20:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/yinrong/.node-gyp/5.0.0/include/node/v8.h:889:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/des-module.cpp:21:12: error: use of undeclared identifier 'ThrowException'; did you mean 'ErrorException'?
    return ThrowException(ErrorException(msg));
           ^~~~~~~~~~~~~~
           ErrorException
../src/des-module.cpp:11:1: note: 'ErrorException' declared here
ErrorException(const char *msg)
^
../src/des-module.cpp:21:27: error: no viable conversion from 'Handle<v8::Value>' (aka 'v8::Local<v8::Value>') to 'const char *'
    return ThrowException(ErrorException(msg));
                          ^~~~~~~~~~~~~~~~~~~
../src/des-module.cpp:11:28: note: passing argument to parameter 'msg' here
ErrorException(const char *msg)
                           ^
../src/des-module.cpp:25:15: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
encrypt(const Arguments &args)
              ^~~~~~~~~
              v8::internal::Arguments
/Users/yinrong/.node-gyp/5.0.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/des-module.cpp:27:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/yinrong/.node-gyp/5.0.0/include/node/v8.h:889:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/des-module.cpp:29:13: error: member access into incomplete type 'const v8::internal::Arguments'
    if (args.Length() != 2)
            ^
/Users/yinrong/.node-gyp/5.0.0/include/node/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/des-module.cpp:31:14: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (!args[0]->IsString())
         ~~~~^~
../src/des-module.cpp:33:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (!Buffer::HasInstance(args[1]))
                             ~~~~^~
../src/des-module.cpp:36:23: error: expected ';' after expression
    String::AsciiValue key(args[0]->ToString());
                      ^
                      ;
../src/des-module.cpp:36:13: error: no member named 'AsciiValue' in 'v8::String'
    String::AsciiValue key(args[0]->ToString());
    ~~~~~~~~^
../src/des-module.cpp:36:32: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    String::AsciiValue key(args[0]->ToString());
                           ~~~~^~
../src/des-module.cpp:37:34: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    Local<Object> data_obj = args[1]->ToObject();
                             ~~~~^~
../src/des-module.cpp:44:30: error: use of undeclared identifier 'key'
    deskey((unsigned char *)*key, EN0, keybuf);
                             ^
../src/des-module.cpp:46:5: error: unexpected namespace name 'Buffer': expected expression
    Buffer *retbuf = Buffer::New(dlen);
    ^
../src/des-module.cpp:46:13: error: use of undeclared identifier 'retbuf'; did you mean 'keybuf'?
    Buffer *retbuf = Buffer::New(dlen);
            ^~~~~~
            keybuf
../src/des-module.cpp:43:19: note: 'keybuf' declared here
    unsigned long keybuf[64] = {0};
                  ^
../src/des-module.cpp:46:22: error: no matching function for call to 'New'
    Buffer *retbuf = Buffer::New(dlen);
                     ^~~~~~~~~~~
/Users/yinrong/.node-gyp/5.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/yinrong/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: requires at least 2 arguments, but 1 was provided

base32 = require('base32')
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/yinrong/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: requires 3 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/yinrong/.node-gyp/5.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
../src/des-module.cpp:47:57: error: use of undeclared identifier 'retbuf'
    unsigned char *ptr = (unsigned char *) Buffer::Data(retbuf);
                                                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/des/src/des-module.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yinrong/test/node_modules/des
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/yinrong/test/package.json'
npm WARN EPACKAGEJSON /Users/yinrong/test No description
npm WARN EPACKAGEJSON /Users/yinrong/test No repository field.
npm WARN EPACKAGEJSON /Users/yinrong/test No README data
npm WARN EPACKAGEJSON /Users/yinrong/test No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "des"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! des@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the des@3.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the des package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls des
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yinrong/test/npm-debug.log
```

**Comment by dmastag** [comment]
Getting the same error wish I knew how to fix it.

**Comment by vitalyTarasiuk** [comment]
Did anyone fix that error ??
